// Advisor explanation tile (Phase F). Sits below the hero verdict and
// reflects the 1-2 sentence human explanation generated by the LLM
// advisor. Lazy: SSR renders an empty placeholder, hydrate fetches
// once on mount, refreshes when the cached snapshot input changes
// (signalled by the verdict signal flipping). Quiet on offline/
// disabled — tile renders a small badge instead of a wall of "loading"
// text.

use leptos::prelude::*;
use serde::Deserialize;

#[allow(dead_code)] // used only in the hydrate-feature fetch path
#[derive(Debug, Clone, Default, Deserialize)]
struct ExplanationEnvelope {
    status: String,
    #[serde(default)]
    data: Option<String>,
}

#[component]
pub fn AdvisorExplanation(verdict: Signal<String>) -> impl IntoView {
    let (state, set_state) = signal::<AdvisorState>(AdvisorState::Loading);

    // Why a setTimeout-after-hydration kickoff instead of Effect::new:
    // an Effect that calls spawn_local synchronously during the
    // hydration sweep was racing with leptos_router's click-handler
    // attachment in the top nav, leaving the toggle unresponsive
    // after deploys. Defer the first fetch until the next animation
    // frame so hydration completes first; subsequent verdict-change
    // refetches still work because we re-arm via a watch-style loop.
    #[cfg(feature = "hydrate")]
    {
        let _ = verdict; // future iteration: refetch eagerly on verdict change
        use leptos::task::spawn_local;
        spawn_local(async move {
            // Yield once so hydration finishes attaching event handlers
            // (top-nav click handlers, SSE EventSource, etc) before we
            // start firing fetches.
            gloo_timers::future::TimeoutFuture::new(0).await;
            loop {
                fetch_and_apply(set_state).await;
                // Re-fetch every minute. Server-side cache absorbs the
                // duplicates on the same input; this keeps us probing
                // for "offline → ok" transitions when the LLM returns.
                gloo_timers::future::TimeoutFuture::new(60_000).await;
            }
        });
    }
    #[cfg(not(feature = "hydrate"))]
    {
        let _ = (verdict, set_state); // silence unused on SSR build
    }

    view! {
        <div class="advisor-tile">
            <span class="advisor-label">"Advisor"</span>
            <span class="advisor-body">
                {move || match state.get() {
                    AdvisorState::Loading => view! {
                        <span class="advisor-state advisor-loading">"…"</span>
                    }.into_any(),
                    AdvisorState::Ready(text) => view! {
                        <span class="advisor-text">{text}</span>
                    }.into_any(),
                    AdvisorState::Offline => view! {
                        <span class="advisor-state advisor-offline">"offline"</span>
                    }.into_any(),
                    AdvisorState::Disabled => view! {
                        <span class="advisor-state advisor-disabled">"disabled"</span>
                    }.into_any(),
                    AdvisorState::Empty => view! {
                        <span class="advisor-state advisor-quiet">"running normally"</span>
                    }.into_any(),
                }}
            </span>
        </div>
    }
}

#[allow(dead_code)] // Ready/Offline/Disabled/Empty constructed only on hydrate
#[derive(Clone, Debug)]
enum AdvisorState {
    Loading,
    Ready(String),
    Offline,
    Disabled,
    Empty,
}

/// Fetch /api/irrigation/explanation and update `setter` with the
/// result. All errors swallowed → AdvisorState::Offline; the dashboard
/// renders a small badge in that case. Only used in the hydrate build
/// (the SSR build never calls fetch).
#[cfg(feature = "hydrate")]
async fn fetch_and_apply(setter: WriteSignal<AdvisorState>) {
    use gloo_net::http::Request;
    let resp = match Request::get("/api/irrigation/explanation").send().await {
        Ok(r) => r,
        Err(_) => {
            setter.set(AdvisorState::Offline);
            return;
        }
    };
    let env = match resp.json::<ExplanationEnvelope>().await {
        Ok(e) => e,
        Err(_) => {
            setter.set(AdvisorState::Offline);
            return;
        }
    };
    match env.status.as_str() {
        "ok" => {
            let text = env.data.unwrap_or_default();
            setter.set(if text.is_empty() {
                AdvisorState::Empty
            } else {
                AdvisorState::Ready(text)
            });
        }
        "disabled" => setter.set(AdvisorState::Disabled),
        _ => setter.set(AdvisorState::Offline),
    }
}
